[2023-10-11T07:07:53.651+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random.inaccurate manual__2023-10-11T07:07:40.835687+00:00 [queued]>
[2023-10-11T07:07:53.670+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random.inaccurate manual__2023-10-11T07:07:40.835687+00:00 [queued]>
[2023-10-11T07:07:53.671+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-11T07:07:53.680+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): inaccurate> on 2023-10-11 07:07:40.835687+00:00
[2023-10-11T07:07:53.690+0000] {standard_task_runner.py:57} INFO - Started process 3302 to run task
[2023-10-11T07:07:53.693+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'random', 'inaccurate', 'manual__2023-10-11T07:07:40.835687+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/randomdag.py', '--cfg-path', '/tmp/tmp7m8_c_bb']
[2023-10-11T07:07:53.697+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask inaccurate
[2023-10-11T07:07:53.743+0000] {task_command.py:415} INFO - Running <TaskInstance: random.inaccurate manual__2023-10-11T07:07:40.835687+00:00 [running]> on host 6a6d3d85ffa3
[2023-10-11T07:07:53.814+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='random' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-10-11T07:07:40.835687+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-11T07:07:40.835687+00:00'
[2023-10-11T07:07:53.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-11T07:07:53.825+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2023-10-11T07:07:53.835+0000] {subprocess.py:86} INFO - Output:
[2023-10-11T07:07:53.840+0000] {subprocess.py:93} INFO - inaccurate
[2023-10-11T07:07:53.840+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-10-11T07:07:53.857+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=random, task_id=inaccurate, execution_date=20231011T070740, start_date=20231011T070753, end_date=20231011T070753
[2023-10-11T07:07:53.910+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-11T07:07:53.926+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
